const {test}=require('node:test');
const assert=require('node:assert/strict');
const C=require('../extension/core.js');
function setup(){const s=C.initial();s.connections=[{id:'source',enabled:true,historyDays:30}];s.projects=[{id:'aurora',name:'Aurora',color:'#89a477'},{id:'boreal',name:'Boreal',color:'#89a477'}];C.ensureLearning(s);return s;}
function record(s,id,title='Aurora planning',allowAI=false){const r=C.normalizeRecord({id,kind:'session',connectorId:'fixture',sourceTitle:title,title,updatedAt:Date.now()-1000,observations:[{connectionId:'source',allowAI}]});s.records.push(r);return r;}
function move(s,r,to,operation){const e=C.userPatch(s,r.id,{projectId:to});e.feedbackId=C.learningFeedback(s,r,e.before,operation);e.after=C.copy(r.user);C.pushUndo(s,[e],'移动');}
const rule=(s,projectId='aurora',keywords=['Aurora'])=>C.learningRuleSave(s,{projectId,keywords});
test('local rules classify denied sessions and browser titles with no model requirement',()=>{const s=setup(),r=record(s,'a');const web=C.normalizeRecord({id:'web',kind:'web',connectorId:'browser',title:'AURORA roadmap',url:'https://example.test',binding:{live:true,epoch:'e'}});web.binding={live:true,epoch:'e'};s.records.push(web);rule(s);assert.equal(C.learningApply(s,['a','web'],{epoch:'e'}).applied,2);assert.equal(r.user.projectId,'aurora');assert.equal(web.user.projectId,'aurora');assert.equal(r.user.manual.projectId,false);});
test('word boundaries exclusions and conflicts cannot silently choose a project',()=>{const s=setup();rule(s);const r=record(s,'a','Auroral');assert.equal(C.learningMatch(s,r).status,'none');r.title=r.sourceTitle='Aurora';rule(s,'boreal');assert.equal(C.learningMatch(s,r).status,'conflict');C.learningProfileSave(s,'boreal',{excludes:['Aurora']});assert.equal(C.learningMatch(s,r).projectId,'aurora');});
test('URL rules require matching origin and path boundary',()=>{const s=setup();C.learningRuleSave(s,{projectId:'aurora',urls:['https://github.com/example/aurora']});const r=record(s,'a','Other');r.url='https://github.com/example/aurora/issues';assert.equal(C.learningMatch(s,r).status,'matched');r.url='https://github.com/example/aurora-copy';assert.equal(C.learningMatch(s,r).status,'none');});
test('three independent records and operations learn, undo removes eligibility',()=>{const s=setup();for(let i=0;i<3;i++){move(s,record(s,'a'+i),'aurora','op'+i);assert.equal(s.learning.rules.some(r=>r.status==='active'),i===2);}C.undo(s);assert.equal(s.learning.rules.some(r=>r.status==='active'),false);});
test('one bulk operation and repeated same record do not qualify',()=>{const s=setup();for(let i=0;i<4;i++)move(s,record(s,'a'+i),'aurora','bulk');assert.equal(s.learning.rules.some(r=>r.status==='active'),false);const r=s.records[0];for(let i=0;i<3;i++){move(s,r,'boreal');move(s,r,'aurora');}assert.equal(s.learning.rules.some(r=>r.status==='active'),false);});
test('correcting learned assignment pauses rule immediately and excludes forbidden derived samples',()=>{const s=setup();for(let i=0;i<3;i++)move(s,record(s,'a'+i),'aurora','op'+i);const r=record(s,'new');C.learningApply(s,[r.id]);assert.equal(r.user.projectId,'aurora');move(s,r,'boreal');assert.equal(s.learning.rules.find(r=>r.projectId==='aurora').status,'paused');assert.equal(C.learningModelProjects(s,s.projects).flatMap(p=>p.examples).length,0);});
test('existing manual assignments seed examples but never invent operations',()=>{const s=C.initial();s.connections=[{id:'source',historyDays:30}];s.projects=[{id:'aurora',name:'Aurora',color:'#89a477'}];for(let i=0;i<4;i++){const r=record(s,'a'+i);C.userPatch(s,r.id,{projectId:'aurora'});}C.ensureLearning(s);C.learningRecompute(s);assert.equal(s.learning.feedback.length,4);assert.ok(s.learning.feedback.every(f=>f.seed&&f.operationId===null));assert.equal(s.learning.rules.length,0);});
test('generic brands do not become learned rules',()=>{for(const name of ['Codex','Claude','AI','开发']){const s=setup();C.saveProject(s,{id:'aurora',name});for(let i=0;i<3;i++)move(s,record(s,'x'+i,name),'aurora','op'+i);assert.equal(s.learning.rules.length,0);}});
test('local cap keeps unmatched records unassigned and respects fixed fields',()=>{const s=setup(),fixed=record(s,'fixed','Other'),r=record(s,'a');move(s,fixed,'boreal');rule(s);const result=C.learningApply(s,['a'],{maxGroups:1});assert.equal(result.applied,0);assert.equal(r.user.projectId,null);move(s,r,'boreal');assert.equal(C.learningApply(s,['a']).applied,0);});
test('rule revision changes invalidate previews and rollback skips later edits',()=>{const s=setup(),r=record(s,'a');const rr=rule(s);s.suggestions=C.learningApply(s,['a'],{history:true,preview:true}).suggestions;C.learningRuleSave(s,{id:rr.id,status:'paused'});assert.equal(C.applySuggestions(s,s.suggestions).conflicts.length,1);C.learningRuleSave(s,{id:rr.id,status:'active'});C.learningApply(s,['a']);C.learningRuleSave(s,{id:rr.id,status:'paused'});s.suggestions=C.learningRollbackPreview(s,rr.id);assert.equal(s.suggestions.length,1);assert.equal(C.applySuggestions(s,s.suggestions).applied,1);assert.equal(r.user.projectId,null);C.learningRuleSave(s,{id:rr.id,status:'active'});C.learningApply(s,['a']);C.userPatch(s,'a',{alias:'A new title'});assert.equal(C.learningRollbackPreview(s,rr.id).length,0);});
test('empty profiles survive pruning but explicitly deleted profiles cannot revive',()=>{const s=setup();rule(s);C.pruneEmptyProjects(s);const r=record(s,'a');assert.equal(C.learningApply(s,['a']).applied,1);assert.ok(s.projects.some(p=>p.id==='aurora'));r.user.projectId=null;s.learning.profiles.find(p=>p.id==='aurora').deleted=true;assert.equal(C.learningMatch(s,r).status,'none');});
test('sample send permission is checked both at capture and at request time',()=>{const s=setup(),r=record(s,'a','Aurora',true);move(s,r,'aurora');assert.equal(C.learningModelProjects(s,s.projects)[0].examples.length,1);r.observations[0].allowAI=false;assert.equal(C.learningModelProjects(s,s.projects)[0].examples.length,0);const denied=record(s,'b','Aurora secret',false);move(s,denied,'aurora');denied.observations[0].allowAI=true;assert.equal(C.learningModelProjects(s,s.projects)[0].examples.length,0);});
test('renaming retains stable rule identity and description edits do not resume paused rules',()=>{const s=setup();C.learningProfileSave(s,'aurora',{keywords:['Aurora']});const rr=s.learning.rules[0];C.learningRuleSave(s,{id:rr.id,status:'paused'});C.saveProject(s,{id:'aurora',name:'Aurora Next'});C.learningProfileSave(s,'aurora',{description:'Revised definition'});assert.equal(rr.projectId,'aurora');assert.equal(rr.status,'paused');assert.equal(s.learning.profiles[0].name,'Aurora Next');});
test('overlapping user rules block learned qualification even with different keywords',()=>{const s=setup();rule(s,'boreal',['planning']);for(let i=0;i<3;i++)move(s,record(s,'overlap'+i),'aurora','op'+i);assert.equal(s.learning.rules.some(r=>r.origin==='learned'&&r.status==='active'),false);});
